### ISSUE TITLE
Unable to import from gdb

### ISSUE THREAD

**Issue by l0stb1t** [cloudburst/libheap#13]
I followed the installation steps. I can import libheap in python but not in gdb.
```
>>> from libheap import *
Not running inside of GDB, exiting...
```

```
gdb-peda$ python from libheap import *
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'libheap'
Error while executing Python code.
```

Found solution in https://github.com/cloudburst/libheap/issues/11.

**Comment by cloudburst** [comment]
Either use the solution in #11 or don't install inside a virtualenv.  I updated the README to remove the virtualenv since you find it confusing.
