### ISSUE TITLE
how to use it  with diffirent glibc version

### ISSUE THREAD

**Issue by 3xp10it** [cloudburst/libheap#15]
"The code needs a complete refactoring to fix this."
If I want it work on my ubuntu16.04 with glibc version=2.23,how should I refactoring it to make it works?

**Comment by cloudburst** [comment]
All of the structures need to match in size and members (struct malloc_state, struct malloc_par):
http://code.metager.de/source/xref/gnu/glibc/malloc/malloc.c#1686

**Comment by cloudburst** [comment]
Hi @3xp10it 

If you try the latest git checkout it should work on glibc 2.23/2.24/2.25 on Ubuntu now.

**Comment by HolmesSherlock** [comment]
Hi **cloudburst**,

In the `It is currently tested and known working on` section of the README, the latest compatible libc on Ubuntu seems to be `v2.23` on `16.04`. Does it need to be updated?

**Comment by cloudburst** [comment]
@HolmesSherlock 

The code supports up to glibc 2.25 which is the latest [released](https://sourceware.org/ml/libc-alpha/2017-02/msg00079.html).  The reason why I have not updated the README is I have not personally tested anything newer than 16.04 on Ubuntu.

If you want to use a different glibc just set the version in the config:
https://github.com/cloudburst/libheap/blob/master/libheap/libheap.cfg#L2

So it should work fine on Ubuntu 16.10 and 17.04, if not please let me know.

**Comment by HolmesSherlock** [comment]
@cloudburst 

I don't think `libc-2.24` on `Ubuntu 16.10` works

**Comment by cloudburst** [comment]
I'll take a look then, but 2.24 on Fedora 25 worked fine for me so I'm not aware of any differences on 16.10

**Comment by HolmesSherlock** [comment]
@cloudburst 

Can you please give the Ubuntu 64 bit version a try?

**Comment by cloudburst** [comment]
Sure, let me setup a VM and try

**Comment by cloudburst** [comment]
@HolmesSherlock 

It is working fine on my setup.  Are you getting any specific errors?

```
bash$ apt-cache policy libc6
libc6:
  Installed: 2.24-3ubuntu2

bash$ apt-cache policy gdb
gdb:
  Installed: 7.11.90.20161005-0ubuntu1

bash$ cat .local/lib/python3.5/site-packages/libheap/libheap.cfg 
[Glibc]
version = 2.24

bash$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.10
Release:        16.10
Codename:       yakkety

bash$ cat .gdbinit 
source /opt/pwndbg/gdbinit.py

python import sys
python sys.path.append('~/.local/lib/python3.5/site-packages/')
python from libheap import *
```

```
bash$ sudo gdb -q -p `pidof gnome-calculator`
pwndbg>

pwndbg> heap
Arena(s) found:
  arena @ 0x7f6dbb49cb00
  arena @ 0x7f6d88000020
  arena @ 0x7f6d94000020
  arena @ 0x7f6d90000020
  arena @ 0x7f6d98000020
  arena @ 0x7f6da4000020
  arena @ 0x7f6da0000020
  arena @ 0x7f6da8000020

pwndbg> heapls 0x7f6d90000020
           ADDR             SIZE            STATUS
sbrk_base  0x7f6d900008b0
chunk      0x7f6d900008b0   0xd20           (F) FD 0x7f6d90000078 BK 0x7f6d90000078 (LC)
chunk      0x7f6d900015d0   0x1060          (inuse)
chunk      0x7f6d90002630   0x1f9d0         (top)
sbrk_end   0x7f6d900228b0
```

**Comment by HolmesSherlock** [comment]
@cloudburst 

Extremely sorry. I changed the `libheap.cfg` in the cloned repository and reinstalled `libheap`. However, I incorrectly assumed that it would change the copy of `libheap.cfg` used by the module residing at `.local/lib/python3.5/site-packages/libheap/libheap.cfg `

**Comment by cloudburst** [comment]
Ah ok.  I think if you use the `--upgrade` pip flag maybe it would copy over the .cfg from the cloned repository like you were expecting.  But I'm not sure.

Sorry, I want to add autodetection of glibc version to automatically set that config file properly but I just have not had time to.

**Comment by HolmesSherlock** [comment]
@cloudburst 

Does `libheap` support `libc-2.24, 32 bit` at the moment?

**Comment by cloudburst** [comment]
Yes it should, I've only tested 32bit support on 2.23 but it should work fine on 2.24.  There are basically no major differences.
