### ISSUE TITLE
where is the definition of c_none, c_title, c_header?

### ISSUE THREAD

**Issue by cainiaocainiao** [cloudburst/libheap#18]
https://github.com/cloudburst/libheap/blob/master/libheap.py#L1252
https://github.com/cloudburst/libheap/blob/master/utils/check_house_of_mind.py#L51

Could someone tell me where is the definition? Thanks

**Comment by cloudburst** [comment]
Sorry that is leftover code, I moved it into:
https://github.com/cloudburst/libheap/blob/master/printutils.py

I fixed that in a2815168ef33985556a0174c15908c91bd461808.  Thank you for the report.

Check_house_of_mind is old and broken I think so not going to fix it at the moment.

**Comment by cloudburst** [comment]
Hi @cainiaocainiao 

If you pull the latest repo these errors should be completely gone.  Thank you.
