### ISSUE TITLE
ERROR - Run command

### ISSUE THREAD

**Issue by HaToan** [cloudburst/libheap#25]
Help me fix error! I cant't not working
gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2)

(gdb) heap
Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'address': 
Error occurred in Python command: 'NoneType' object has no attribute 'address'

**Comment by cloudburst** [comment]
Do you have debug symbols installed?

`apt-get install libc6-dbg`

**Comment by thinkycx** [comment]
Also confused with this problem.
Solved by  `apt-get install libc6-dbg:i386`.
