### ISSUE TITLE
Python Exception <class 'AttributeError'>

### ISSUE THREAD

**Issue by hackerbuck** [cloudburst/libheap#27]
hey , 
i came a across a weird behavior today  libheap was throwing this error 
```
Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'address': 
Error occurred in Python command: 'NoneType' object has no attribute 'address'
``` 
while it is working properly for all other binary except one  particular binary that i am trying to reverse
I have installed libc6-dbg , libc6-dbg:i386

Any suggestions on how I can fix this?

**Comment by cloudburst** [comment]
Unfortunately I'm not sure since that error message could come from anywhere.  You would have to debug the code some to figure out which object is not being read properly due to symbol error or whatever.

**Comment by cloudburst** [comment]
Please reopen with more information such as a binary or some way I can help you reproduce the error.
