### ISSUE TITLE
How can use it in Kali 2.0-64bit?

### ISSUE THREAD

**Issue by pyang1997** [cloudburst/libheap#31]
glibc version is 2.27.
When I use it. It will " 'NoneType' object has no attribute 'address' "

**Comment by cloudburst** [comment]
Hi currently there is no support for tcache in glibc 2.26/2.27.  libheap needs to be patched to support this.

https://sourceware.org/git/gitweb.cgi?p=glibc.git;a=commit;h=d5c3fafc4307c9b7a4c7d5cb381fcdbfad340bcc
