### ISSUE TITLE
heap.png how to extend?

### ISSUE THREAD

**Issue by filipkilibarda** [cloudburst/libheap#34]
Hey,

I really like the heap flowchart you've made, and it's the only good chart I can find. I'm working with later versions of glibc that have increased their heap corruption checks and I'd love to extend the chart. Do you still have the source file for the flowchart? So I can move boxes around and add new ones. I'm currently just using a drawing tool to annotate the .png and it's getting really cluttered.

Thanks!

**Comment by cloudburst** [comment]
Sure but it's a Microsoft Visio file.  If you want that I'm happy to send somehow?  I have open twitter DMs if you want to send me your email or can comment here or whatever is easier.

**Comment by filipkilibarda** [comment]
Maybe you could push the file to this repo? In case someone else wants to do the same thing. 

~~If you still have a Microsoft Visio license, it might be helpful for me if you could open it up, save it as an svg, then push the svg as well. That way I can edit the svg in inkscape and avoid trying to get my hands on a microsoft visio license.~~

**Comment by filipkilibarda** [comment]
Actually it looks like draw.io has a feature for importing Microsoft Visio files! Forget the svg idea

**Comment by cloudburst** [comment]
That's good as I don't have Visio or a license anymore haha.  Also I'd rather not push it as I don't know a way to strip the metadata on the visio file.

**Comment by filipkilibarda** [comment]
Alright, sent you a message on twitter.
